---

- block:
    - validate:
        schema:
          type: object
          properties:
            authorized_keys:
              type: object
              patternProperties:
                "^[A-Za-z0-9_]+$":
                  type: array
                  items:
                    type: string
                  minLength: 1
            exclusive:
              type: boolean
              default: false
          required:
            - authorized_keys
            - exclusive
        instance: "{{ ssh }}"
      register: ssh_validated

    - set_fact:
        ssh_v: "{{ ssh_validated.result }}"

    - name: "Authorize ssh public keys"
      authorized_key:
        exclusive: "{{ ssh_v.exclusive }}"
        key: "{{ item.value | join('\n') }}"
        user: '{{ item.key }}'
      with_dict: "{{ ssh_v.authorized_keys }}"

  tags:
    - ssh_authorize_keys
