---

- block:
    - validate:
        schema:
          type: object
          properties:
            authorized_keys:
              type: array
              items:
                type: string
              minLength: 1
            exclusive:
              type: boolean
              default: false
            user:
              type: string
              default: ubuntu
          required:
            - exclusive
            - keys
            - user
        instance: "{{ ssh }}"
      register: ssh_validated

    - set_fact:
        ssh_v: "{{ ssh_validated.result }}"

    - name: "Authorize {{ ssh_v.keys | length }} ssh keys for user {{ ssh_v.user }}"
      authorized_key:
        exclusive: "{{ ssh_v.exclusive }}"
        key: "{{ ssh_v.keys | join('\n') }}"
        user: '{{ ssh_v.user }}'
  tags:
    - ssh_authorize_keys
