---

- block:
    - validate:
        schema:
          type: object
          properties:
            agent_forwarding_enabled:
              type: boolean
              default: no
            allowed_users:
              type: array
              items:
                type: string
              minLength: 1
              default:
                - ubuntu
            tun_device_forwarding_enabled:
              type: boolean
              default: no
            sftp_enabled:
              type: boolean
              default: yes # Ansible just works better over sftp than scp
          required:
            - agent_forwarding_enabled
            - allowed_users
            - tun_device_forwarding_enabled
            - sftp_enabled
        instance: "{{ ssh }}"
      register: ssh_validated

    - set_fact:
        ssh_v: "{{ ssh_validated.result }}"

    - block:
        # It seems like the user account is locked initially but the locked state is not enforced.
        # If PAM is then disabled, we will be locked out. The harding disables PAM
        - name: 'Unlock the user account'
          user:
            name: '{{ ansible_user }}'
            password: '*'

        - name: 'Harden ssh client and server'
          import_role:
            name: dev-sec.ssh-hardening
          vars:
            sftp_enabled: '{{ ssh_v.sftp_enabled }}'
            ssh_allow_agent_forwarding: '{{ ssh_v.agent_forwarding_enabled }}'
            ssh_allow_tcp_forwarding: yes # does not decrease security
            ssh_allow_users: "{{ ssh_v.allowed_users | join(' ') }}"
            ssh_hardening_enabled: yes
            ssh_permit_tunnel: "{{ ssh_v.tun_device_forwarding_enabled }}"
      become: yes
  tags:
    - ssh_harden
